project:
  title: "taxprofiler-manuscript"
  type: website

format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
  pdf:
    documentclass: article
    colorlinks: true
    highlight-style: github
    fontfamily: libertinus
    keep-tex: true
    template-partials:
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
